### PR TITLE
ruby 2.5.1

### PR DESCRIPTION
**Pull request by fd00**
try to package ruby 2.5.1

* update fedora url
* add new fedora patches
* remove unapplicable patches

logs : https://gist.github.com/fd00/9273434babe316334e18ea1649c2baca

### CODE REVIEW

**Comment by yselkowitz** [comment]
I have been working on 2.5.1, which I just pushed to git for the sake of this discussion.  Unfortunately, I have been getting SEGVs in rdoc on 32-bit only which have prevented me from completing the upgrade, and I haven't had time to debug it.  Did you try on 32-bit?

**Comment by fd00** [comment]
> I have been working on 2.5.1, which I just pushed to git for the sake of this discussion.

Thanks!

> Did you try on 32-bit?

Not yet. But I'll try it.

**Comment by fd00** [comment]
@yselkowitz 
Can you tell me how to prepare i686-pc-cygwin building environment on x86_64-cygwin if possible?

**Comment by yselkowitz** [comment]
Simply install 32-bit cygwin with the 32-bit installer in a separate directory from your 64-bit installation.  They can peacefully coexist side-by-side.

**Comment by fd00** [comment]
I reproduce SEGV in rdoc on 32-bit. 
* https://gist.github.com/fd00/e809af3676788dd0126fee3d0933f7d8

But gdb couldn't catch it.
* https://gist.github.com/fd00/a6d801237a2fee6bdd325863b060e0e4

It seems that ruby's internal handler catches SEGV. 
* https://github.com/ruby/ruby/blob/v2_5_1/signal.c#L924

Do you know how to catch SEGV?

**Comment by yselkowitz** [comment]
Sorry, never had to debug ruby before.  Does strace give anything useful?

**Comment by yselkowitz** [comment]
Would https://bugs.ruby-lang.org/issues/13999 be related somehow?

**Comment by fd00** [comment]
Assignee (hsbt) said that he has not been able to confirm the issue. (I met him directly.)

**Comment by jon-turney** [comment]
> Do you know how to catch SEGV?

gdb should get a chance to handle the SEGV before the signal handler is run.

Possibly you need 'set cygwin-exceptions on'

See https://cygwin.com/faq.html#faq.programming.debugging-cygwin

**Comment by svnpenn** [comment]
https://github.com/cygwinports/ruby/issues/1

**Comment by fd00** [comment]
I couldn't handle SIGSEGV though 'set cygwin-exception on'
(signal handler seems to be run)

**Comment by fd00** [comment]
> Unfortunately, I have been getting SEGVs in rdoc on 32-bit only

This problem seems resolved in 2.6. Please try it.

**Comment by fd00** [comment]
I will submit a new pull request (for ruby 2.6.0), so I will close this PR.

**Comment by cup** [comment]
https://github.com/cygwinports/ruby/issues/1
https://github.com/cygwinports/ruby/pull/2
https://github.com/cygwinports/ruby/pull/3
https://github.com/fd00/yacp/issues/21

**Pull request closed without merging**
